SELECT HT.TEAM_NAME, HT.TEAM_ID
FROM TEAM HT JOIN SCHEDULE ON HT.TEAM_ID = SCHEDULE.HOMETEAM_ID #홈 경기가 있는 팀만 본다
WHERE HT.TEAM_ID NOT IN( SELECT HOMETEAM_ID
						FROM SCHEDULE SC
						WHERE HOME_SCORE < AWAY_SCORE )
GROUP BY TEAM_ID;
